# Generated by Django 4.2.4 on 2023-08-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='effects',
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
    ]
