# Generated by Django 4.2.4 on 2023-08-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0002_remove_skill_effects_delete_effect_skill_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='effects',
            field=models.TextField(),
        ),
    ]
