# Generated by Django 4.2.4 on 2023-09-01 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0005_keyvalue_item_consumable_skill_passive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='restrictions',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='effects',
        ),
        migrations.DeleteModel(
            name='KeyValue',
        ),
        migrations.AddField(
            model_name='restriction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameData.item'),
        ),
        migrations.AddField(
            model_name='effect',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameData.skill'),
        ),
    ]
