# Generated by Django 4.2.4 on 2023-09-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0006_effect_restriction_remove_item_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='skills',
            field=models.ManyToManyField(blank=True, to='GameData.skill'),
        ),
    ]
