# Generated by Django 4.2.4 on 2023-08-31 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Gangs', '0001_initial'),
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Entity.entity')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gangs.gang')),
            ],
            bases=('Entity.entity',),
        ),
        migrations.AddField(
            model_name='entity',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
