# Generated by Django 4.2.4 on 2023-08-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0001_initial'),
        ('Entity', '0002_character_entity_level_delete_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='items',
            field=models.ManyToManyField(to='GameData.item'),
        ),
        migrations.AddField(
            model_name='entity',
            name='skills',
            field=models.ManyToManyField(to='GameData.skill'),
        ),
    ]
