# Generated by Django 4.2.4 on 2023-09-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0006_effect_restriction_remove_item_restrictions_and_more'),
        ('Entity', '0003_entity_items_entity_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='GameData.item'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='GameData.skill'),
        ),
    ]
