# Generated by Django 4.2.4 on 2023-09-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GameData', '0006_effect_restriction_remove_item_restrictions_and_more'),
        ('Entity', '0004_alter_entity_items_alter_entity_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='items',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('equipped', models.IntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.character')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameData.item')),
            ],
        ),
    ]
